### ISSUE TITLE
Hi. Please support Activiti.

### ISSUE THREAD

**Issue by XenoAmess** [valb3r/flowable-bpmn-intellij-plugin#191]
**Is your feature request related to a problem? Please describe.**
Hi.
Out team need to use Activiti but there be no good plugin to use.
I know flowable is quite similar to Activiti in many ways, so I wonder if you could make there an option for creating/editing bpmn files for activiti namespace, but not flowable?

**Describe the solution you'd like**
I would like you do that.

**Describe alternatives you've considered**
Otherwise there be possibility that I fork it and do a TPM for activiti.
But that is NOT elegant.

**TODO LIst:**
- [x] Initialize XML parsing module
- [x] Update XML test files in new module to Activity
- [x] Fix mapping tests (Activity)
- [x] Add new Activity plugin
- [x] Ensure that Activity plugin has no unavailable options (like properties, custom elements from Flowable (Collapsed subprocess)
- [x] ~Intellij menu item filter (open file) based on XML namespace to detect dialect~ Won't do, maybe as separate feature

**XML Update list:**
- [x] ./transactional-collapsed-subprocess.bpmn20.xml
- [x] ./nested-interlaced.bpmn20.xml
- [x] ./empty-process-name.bpmn20.xml
- [x] ./popurri.bpmn20.xml (basic currently - no nested property stuff)
- [x] ./duplicates.bpmn20.xml
- [x] ~./simple-collapsed-subprocess.bpmn20.xml~ (Not supported by Activity 6.x)
- [x] ~./custom-service-tasks/http-task.bpmn20.xml~ (Not supported by Activity 6.x)
- [x] ./custom-service-tasks/script-task.bpmn20.xml
- [x] ./custom-service-tasks/camel-task.bpmn20.xml
- [x] ./custom-service-tasks/user-task.bpmn20.xml
- [x] ./custom-service-tasks/custom/camel-task-no-ext.bpmn20.xml
- [x] ./custom-service-tasks/custom/camel-task-no-string.bpmn20.xml
- [x] ./custom-service-tasks/custom/camel-task-no-field.bpmn20.xml
- [x] ./custom-service-tasks/business-rule-task.bpmn20.xml
- [x] ~./custom-service-tasks/shell-task.bpmn20.xml~ (Not supported by Activity 6.x)
- [x] ./custom-service-tasks/mule-task.bpmn20.xml
- [x] ./custom-service-tasks/receive-task.bpmn20.xml
- [x] ./custom-service-tasks/decision-task.bpmn20.xml
- [x] ./custom-service-tasks/mail-task.bpmn20.xml
- [x] ./custom-service-tasks/service-task.bpmn20.xml
- [x] ./custom-service-tasks/manual-task.bpmn20.xml
- [x] ./nested.bpmn20.xml
- [x] ./simple-nested.bmpn20.xml

**Flowable plugin:**
- [ ] Support Manual Task (missing in popurri.xml, but is supported) - modify tests

**Comment by valb3r** [comment]
Hi, dialect support is already present to some extent by the plugin architecture (this is why it has `flowable-xml-parser` - to support multiple dialects).
I think I can add support for the Activity as well, but it will take couple of weeks from now (depending on my free time).

**Comment by XenoAmess** [comment]
> Hi, dialect support is already present to some extent by the plugin architecture (this is why it has `flowable-xml-parser` - to support multiple dialects).

Yep, already found it can read the attributes.

> I think I can add support for the Activity as well, but it will take couple of weeks from now (depending on my free time).

Great, many thanks.

**Comment by valb3r** [comment]
@XenoAmess 
Which BPMN editor you currently use for Activity? I need to create example XML diagrams for tests. 
Their 7.x modeler is very stripped-off thing

**Comment by valb3r** [comment]
@XenoAmess Published plugin, you can install it by following
https://plugins.jetbrains.com/plugin/15222-activiti-bpmn-visualizer

It should be publicly available in a couple of days

**Comment by XenoAmess** [comment]
> @XenoAmess Published plugin, you can install it by following
> https://plugins.jetbrains.com/plugin/15222-activiti-bpmn-visualizer
> 
> It should be publicly available in a couple of days

Many thanks!!!!!
Already using it, and it is really good!
Thank you for the great donation!
